#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'postgresql',
  :git => 'https://github.com/findsyou/cookbooks',
  :ref => 'postgresql-improvements'

cookbook 'rbenv', '~> 1.7.1'
cookbook 'unicorn', '~> 2.0.0'
cookbook 'nginx', '~> 2.7.4'